import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Sensational' : 'Sensational'}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex  h-14 items-center px-4 justify-between shadow-md'>
            <Link href='/'>
              <div className='text-black text-lg font-bold'>Sensational</div>
            </Link>
            <div className='flex'>
              <Link href='/cart'>
                <div className='text-black p-2'>Cart</div>
              </Link>
              <Link href='/login'>
                <div className='text-black p-2'>Login</div>
              </Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4 px-4'>{children}</main>
        <footer className='flex h-12 justify-center items-center shadow-inner'>
          <p>Copyright © 2022 Sensational</p>  
        </footer>
      </div>
    </>
  );
}
