import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Sensational' : 'Sensational'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav >
            <Link href="/">
              <div className='text-lg font-bold'>Sensational</div>
            </Link>
            <div>
              <Link href="/cart">
                <div>Cart</div>
              </Link>
              <Link href="/login">
                <div>Login</div>
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>
        <footer>Footer</footer>
      </div>
    </>
  );
}
